FROM docker.io/library/python:3.14.2-alpine3.23
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN apk add --no-cache openssl && \
    pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "-V"]
