[project]
name = "front"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gerald-scharitzer" }
]
requires-python = ">=3.14"
dependencies = [
    "reflex>=0.9.11.post1",
]

[project.scripts]
front = "front:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
